apiVersion: apps/v1
kind: Deployment
metadata:
  name: pragati-backend
  labels:
    app: pragati-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pragati-backend
  template:
    metadata:
      labels:
        app: pragati-backend
    spec:
      containers:
      - name: backend
        image: pragati/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "pragati"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/pragati"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch-service:9200"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: pragati-backend-service
spec:
  selector:
    app: pragati-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
